### ISSUE TITLE
Open to collaborators

### ISSUE THREAD

**Issue by datatalking** [je-suis-tm/web-scraping#23]
I've just found your codebase and there are a few things I would like to add if you are open to having collaborators. The documentation so far is really good, I'd like to improve upon that and test out other sites that web-scraping was disabled or not working anymore.

**Comment by je-suis-tm** [comment]
Hi datatalking, I am open to have collaborators. Tell me more about what you plan to do. Do u intend to update some of the website scrappers regularly?

**Comment by datatalking** [comment]
There are lots of idea but i'm not sure they are all feasible.

I'm more skilled on the data modeling and analysis side, so I'm tired of not know how to scrape very well but my background is analysis not coding. So then looking at the 'inspect element' meta HTML then correctly parsing that down into 'h5' tag is  "good", "general" or "garbage" isn't what I know. Then again it could be some "variable" that indicates another but I'm not yet fluent in "Webdeveloper-ese". Was hoping to dig deeper in your code, learn from you, while I document, add tests.

Had a question come up today in fact, is there a way we can run a test to see if a website has exposed elements we can scrape? Like if it has the cloudfare markers then the odds go down? I usually find out it was cloudfare after I google the error for sometimes an hour. '404 error' or '403 error' '503 Service Unavailable', or '504 Gateway Timeout errorsvs' instead we give `web-scrapingError-Cloudfare47` meaning we can only get 47 % of what we maximally did. 

Guess I figure best way to learn is to work on it. My home-brew method isn't sustainable I only have partial Morningstar, trendingeconomics, Bloomberg, and Marketwatch and is giving less and less data, just lost two more this year but I have backups. So recoding something or spending forever trying to learn how to debug a new issue for every new project or data sources isn't working. When I'm active its 12 to 15 hrs a day infant of a keyboard.

**Comment by je-suis-tm** [comment]
Like you, I am not a computer science/software engineering background. I learned a lot of things from data engineers. The thing about web scraping is there are different ways to do it. Think of it as offense vs defense. Some websites such as Bloomberg deploy the cutting edge technology to differentiate bot from human users. Websites like this require selenium to simulate how human interacts on a browser. Other websites use CSRF tokens which you need to include some special tokens in the header to avoid any captcha check. In one word, there is no panacea. It is a time-consuming otherwise data engineers wont be in high demand. My experience told me, an influential website such as Bloomberg is likely to be mirrored by many smaller websites. You can save a lot of time and effort by simply scraping the mirrored websites.

**Comment by je-suis-tm** [comment]
If there's nothing else, I will close the issue?
